from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd

from .config import resolve_project_path


@dataclass(frozen=True)
class ProfileEntry:
    model: str
    scale_b: float
    quant: str
    context_len: int
    prefill_tokens: int
    decode_tokens: int
    prefill_j_per_tok: float
    decode_j_per_tok: float
    tokens_per_sec: float
    peak_mem_gb: float
    gpu_power_w: float
    seed: int
    run_id: str


PROFILE_COLUMNS = [
    "model",
    "scale_b",
    "quant",
    "context_len",
    "prefill_tokens",
    "decode_tokens",
    "prefill_j_per_tok",
    "decode_j_per_tok",
    "tokens_per_sec",
    "peak_mem_gb",
    "gpu_power_w",
    "seed",
    "run_id",
]


MODEL_NAMES = {
    1.7: "Qwen/Qwen3-1.7B",
    3.0: "Qwen/Qwen2.5-3B-Instruct",
    8.0: "Qwen/Qwen3-8B",
}

QUANT_FACTOR = {
    "FP16": {"mem": 2.0, "energy": 1.00, "speed": 1.00},
    "INT8": {"mem": 1.05, "energy": 0.66, "speed": 1.28},
    "INT4": {"mem": 0.58, "energy": 0.46, "speed": 1.58},
}


def default_parameterized_profile() -> pd.DataFrame:
    """Create a deterministic profile used until remote 4090 measurements are supplied.

    The numbers are generated by explicit scaling laws rather than hard-coded plots:
    model memory scales with parameter count and quantization; KV memory scales
    linearly with context; token energy scales sublinearly with parameter count and
    separately for prefill/decode. Remote benchmark CSVs can replace this file
    without changing the simulator or paper pipeline.
    """

    rows: list[dict[str, object]] = []
    contexts = [512, 1024, 2048, 4096, 8192]
    for scale in [1.7, 3.0, 8.0]:
        for quant, factors in QUANT_FACTOR.items():
            for ctx in contexts:
                resident_mem = scale * factors["mem"] * 0.92
                kv_mem = scale * ctx * (0.00024 if quant == "INT4" else 0.00032 if quant == "INT8" else 0.00048)
                overhead = 0.55 + 0.00005 * ctx
                peak_mem = resident_mem + kv_mem + overhead
                base_energy = 0.0105 * (scale ** 0.88) * factors["energy"]
                prefill_e = base_energy * 0.74 * (1.0 + ctx / 20000.0)
                decode_e = base_energy * 1.46 * (1.0 + ctx / 28000.0)
                tps = 92.0 / (scale ** 0.82) * factors["speed"] * (1.0 - min(ctx, 8192) / 50000.0)
                power_w = min(310.0, max(120.0, tps * decode_e * 1.8 + 95.0))
                rows.append(
                    {
                        "model": MODEL_NAMES[scale],
                        "scale_b": scale,
                        "quant": quant,
                        "context_len": ctx,
                        "prefill_tokens": ctx,
                        "decode_tokens": 128,
                        "prefill_j_per_tok": round(prefill_e, 6),
                        "decode_j_per_tok": round(decode_e, 6),
                        "tokens_per_sec": round(tps, 3),
                        "peak_mem_gb": round(peak_mem, 3),
                        "gpu_power_w": round(power_w, 2),
                        "seed": 0,
                        "run_id": "parameterized_anchor_v1",
                    }
                )
    return pd.DataFrame(rows, columns=PROFILE_COLUMNS)


def write_default_profile(path: str | Path) -> Path:
    out = resolve_project_path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    df = default_parameterized_profile()
    df.to_csv(out, index=False)
    return out


def load_profile(path: str | Path) -> pd.DataFrame:
    p = resolve_project_path(path)
    if not p.exists():
        write_default_profile(p)
    df = pd.read_csv(p)
    missing = [c for c in PROFILE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"profile is missing columns: {missing}")
    return aggregate_profile(df)


def aggregate_profile(df: pd.DataFrame) -> pd.DataFrame:
    """Average repeated benchmark runs into one scheduler-facing profile row."""

    keys = ["model", "scale_b", "quant", "context_len", "prefill_tokens", "decode_tokens"]
    numeric = ["prefill_j_per_tok", "decode_j_per_tok", "tokens_per_sec", "peak_mem_gb", "gpu_power_w"]
    if df.duplicated(keys).any():
        grouped = df.groupby(keys, as_index=False, sort=True)
        out = grouped[numeric].mean()
        out["seed"] = 0
        out["run_id"] = "measured_4090_mean"
        return out[PROFILE_COLUMNS]
    return df[PROFILE_COLUMNS].copy()


def nearest_profile_row(profile: pd.DataFrame, scale_b: float, quant: str, context_len: int) -> pd.Series:
    candidates = profile[profile["quant"].str.upper() == quant.upper()].copy()
    if candidates.empty:
        raise ValueError(f"no profile rows for quant={quant}")
    candidates["_dist"] = (candidates["scale_b"] - scale_b).abs() * 100000 + (candidates["context_len"] - context_len).abs()
    return candidates.sort_values("_dist").iloc[0]


def profile_table_rows(profile: pd.DataFrame, quant: str, context_len: int = 2048) -> Iterable[dict[str, object]]:
    for scale in sorted(profile["scale_b"].unique()):
        row = nearest_profile_row(profile, float(scale), quant, context_len)
        yield {
            "model": f"{float(scale):g}B",
            "quant": quant,
            "throughput": float(row["tokens_per_sec"]),
            "prefill_mj": float(row["prefill_j_per_tok"]) * 1000.0,
            "decode_mj": float(row["decode_j_per_tok"]) * 1000.0,
            "peak_mem": float(row["peak_mem_gb"]),
        }
